name: Blog Auto Batch

on:
  schedule:
    - cron: '50 21 * * *' # 한국시간 오전 6:50에 해당 (21:50 UTC 전날)
  workflow_dispatch:

jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run news-crawling.js
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node news-crawling.js

      - name: Upload error screenshots (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: |
            mainFrame_not_found_*.png
